name: ohjolly
favicon: null
layout_spectrum: 0.8830764365848154
typography_spectrum: 0.5082691938150674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5ceec'
    - '#050808'
    - '#38578d'
    - '#fcfcfc'
    - '#a16e60'
  brandStrength: 0.5899218481499702
  lightness: 0.7506828657351434
  saturation: 0.18273059115745127
  rhythmicContrast: 0.12495192233473063
purpose: []
